version: "3.7"
services:
  db:
    image: mariadb:latest
    # restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: test-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_TCP_PORT: 3306
  phpmyadmin:
    links:
      - db:db
    image: phpmyadmin/phpmyadmin
    # restart: always
    ports:
      - "8080:80"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:
